name: Build and Run Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 20
    runs-on: 8-cores
    steps:
      - uses: actions/checkout@v3
      #----------------------------------------------
      #  -----  set-up python  -----
      #----------------------------------------------
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.11"
      #----------------------------------------------
      #  -----  install & configure poetry  -----
      #----------------------------------------------
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: console-test/.venv
      #----------------------------------------------
      #  -----  install dependencies  -----
      #----------------------------------------------
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      #  -----  install vega binaries. -----
      #----------------------------------------------
      - name: Install vega binaries
        run: poetry run python -m vega_sim.tools.load_binaries --force --dev --version v0.72.1-13289-35c9c9c8
      #----------------------------------------------
      #  -----  pull console. -----
      #----------------------------------------------
      - name: pull console
        run: |
          poetry run docker pull vegaprotocol/trading:develop
      #----------------------------------------------
      #  -----  install playwright. -----
      #----------------------------------------------
      - name: Install Playwright
        run: poetry run playwright install
      #----------------------------------------------
      #  ----- run tests. -----
      #----------------------------------------------
      - name: Run tests
        run: poetry run pytest -v -s --numprocesses 4 --dist loadfile --durations=20 --reruns 1 --reruns-delay 5
      #----------------------------------------------
      #  -----  upload traces  -----
      #----------------------------------------------
      - name: Upload Playwright Trace
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-trace
          path: ./traces/
          retention-days: 15
