name: Playwright Tests poetry
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'
    - name: Install Poetry
      uses: snok/install-poetry@v1   

    - name: Install dependencies
      run: |
        poetry install --no-root

    - name: load Binaries
      run: |    
        poetry run python -m vega_sim.tools.load_binaries

    - name: pull console
      run: |    
        poetry run docker pull vegaprotocol/trading:testnet

    - name: install playwright
      run:
        poetry run playwright install
    - name: run tests
      run:
        poetry run pytest --numprocesses auto

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
