name: Playwright Tests poetry
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.6'
    - name: Install Poetry
      uses: snok/install-poetry@v1   

    - name: Install dependencies
      run: |
        poetry install

    - name: load Binaries
      run: |    
        python vega_sim.tools.load_binaries
        
    - name: pull console
      run: |    
        docker pull vegaprotocol/trading:testnet

    - name: Run your tests
      run: poetry run pytest

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
