name: Build and Run Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  
jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'
    - name: Install Poetry
      uses: snok/install-poetry@v1   

    - name: Install dependencies
      run: |
        poetry install --no-root

    - name: load Binaries
      run: |    
        poetry run python -m vega_sim.tools.load_binaries

    - name: pull console
      run: |    
        poetry run docker pull vegaprotocol/trading:testnet

    - name: install playwright
      run:
        poetry run playwright install
    - name: run tests
      run:
        poetry run pytest --numprocesses auto

    - name: Upload Playwright Trace
      uses: actions/upload-artifact@v3
      if: always()
      with:
          name: playwright-trace
          path: ./traces/
          retention-days: 30

    - name: Upload Playwright Traces
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-trace
        retention-days: 30
        path: |
        
          # List all the trace files in the 'traces' folder
          traces=$(find ./traces/ -type f)
        
          # Iterate over each trace file and upload it individually
          for trace in $traces; do
            trace_name=$(basename "$trace")
            echo "Uploading trace: $trace_name"
            echo "::set-env name=TRACE_PATH::$trace" # Set an environment variable for future reference if needed
            tar -czf "$trace_name.tar.gz" "$trace" # Compress the trace file
            echo "::add-path::$trace_name.tar.gz" # Add the compressed file to the list of artifacts to upload
          done
        
        