name: Build and Run Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 20
    runs-on: console-test
    steps:
      - uses: actions/checkout@v3
      #----------------------------------------------
      #  -----  install dependencies  -----
      #----------------------------------------------
      - run: ulimit
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      #----------------------------------------------
      #  -----  install vega binaries. -----
      #----------------------------------------------
      - name: Install vega binaries
        run: poetry run python -m vega_sim.tools.load_binaries --force
      #----------------------------------------------
      #  -----  pull console. -----
      #----------------------------------------------
      - name: pull console
        run: |
          poetry run docker pull vegaprotocol/trading:develop
      #----------------------------------------------
      #  -----  install playwright. -----
      #----------------------------------------------
      - name: Install Playwright
        run: poetry run playwright install --with-deps chromium
      #----------------------------------------------
      #  ----- run tests. -----
      #----------------------------------------------
      - name: Run tests
        run: poetry run pytest -v -s --numprocesses auto --dist loadfile --durations=20
      #----------------------------------------------
      #  -----  upload traces  -----
      #----------------------------------------------
      - name: Upload Playwright Trace
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-trace
          path: ./traces/
          retention-days: 15
